global proc FileLocator() {};
string $FileInfo = `whatIs FileLocator`;
string $InstallPath = `substring FileLocator 25 999`;
string $PluginDir = `dirname $InstallerPath`;

string $pythonCmd = "import sys;";
$pythonCmd += "sys.path.append('" + $PluginDir + "');";
$pythonCmd += "import install;";
$pythonCmd += "import importlib;";
$pythonCmd += "importlib.reload(install);";
$pythonCmd += "install.Run()";

python($pythonCmd)